# Generated by Django 4.0 on 2022-10-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationships',
            name='user_follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_follower_data', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='user_following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_following_data', to='users.customuser'),
        ),
    ]
