# Generated by Django 4.0 on 2022-04-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_favorite_recipes'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationships',
            name='user_follower',
        ),
        migrations.AddField(
            model_name='relationships',
            name='user_follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_follower_data', to='users.customuser'),
        ),
        migrations.RemoveField(
            model_name='relationships',
            name='user_following',
        ),
        migrations.AddField(
            model_name='relationships',
            name='user_following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_following_data', to='users.customuser'),
        ),
    ]
