version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/python:3.8.10
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run: python manage.py test

workflows:
  main:
    jobs:
      - tests:
          context:
            - P13_OC_BACKEND_ENV